# Generated by Django 3.2.7 on 2021-09-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
