# Generated by Django 3.2.7 on 2021-09-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20210908_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile.company', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'CUSTOMER'), ('PROVIDER', 'PROVIDER')], max_length=15, null=True, verbose_name='Тип пользователя'),
        ),
    ]
