# Generated by Django 3.2.7 on 2021-09-24 11:13
from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.conf import settings


def add_superuser(app, schema_editor):
    user = app.get_model('profile', 'User').objects.create(
        username='admin@admin.com',
        email='admin@admin.com',
        is_superuser=True,
        is_staff=True,
        password=make_password('admin')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210913_1648'),
    ]

    operations = [
        migrations.RunPython(add_superuser),
    ]
