# Generated by Django 3.2.7 on 2021-09-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Цена')),
                ('amount', models.IntegerField(default=1, max_length=10000, verbose_name='Кол-во')),
                ('available', models.BooleanField(default=True, verbose_name='Доступе для продажи')),
                ('description', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sellers', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Ассортимент',
                'verbose_name_plural': 'Ассортимент',
            },
        ),
    ]
