# Generated by Django 3.2.7 on 2021-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
