# Generated by Django 3.2.7 on 2021-09-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0002_alter_assortment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assortment',
            old_name='amount',
            new_name='quantity',
        ),
    ]
