# Generated by Django 3.2.7 on 2021-09-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together={('product', 'feature')},
        ),
    ]
