FROM python:3.8
COPY ../../../app /app
ENV DB_NAME=postgres
ENV DB_LOGIN=postgres
ENV DB_PASSWORD=postgres
ENV DB_ADDRESS=postgres
ENV DB_PORT=5432
ENV CELERY_BROKER_ADDRESS=redis
ENV CELERY_BROKER_DB=1
ENV CELERY_BACKEND_ADDRESS=redis
ENV CELERY_BACKEND_DB=2
RUN pip install gunicorn
RUN pip install -r /app/requirements.txt
WORKDIR /app
