version: '3.8'

services:
  redis:
    image: redis
    expose:
      - 6379
  celery:
    build:
      context: ./celery
    command: celery -A tasks.tasks worker --loglevel=INFO -P eventlet
    env_file:
      - celery/.env
    depends_on:
      - redis
    expose:
      - 6379
    ports:
      - 25:25
      - 465:465
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: ./web
    command: gunicorn --bind 0.0.0.0:5000 shop.wsgi:application
    expose:
      - 5000
    depends_on:
      - migration
  migration:
    build:
      context: ./web
    command: python manage.py migrate
    depends_on:
      - celery
      - redis
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web
