# Generated by Django 3.2.7 on 2021-09-08 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('housing', models.IntegerField(blank=True, null=True, verbose_name='Строение')),
                ('structure', models.IntegerField(blank=True, null=True, verbose_name='Корпус')),
                ('apartment', models.CharField(max_length=20, verbose_name='Квартира или Офис')),
                ('additional_info', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
