# Generated by Django 3.2.7 on 2021-09-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210913_1648'),
        ('assortment', '0003_rename_amount_assortment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortment',
            name='user',
        ),
        migrations.AddField(
            model_name='assortment',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='profile.company', verbose_name='Продавец'),
            preserve_default=False,
        ),
    ]
