# Generated by Django 3.2.7 on 2021-09-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210913_1648'),
        ('product', '0004_auto_20210914_1435'),
        ('assortment', '0004_auto_20210913_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_assortment', to='profile.company', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_assortment', to='product.product', verbose_name='Товар'),
        ),
    ]
