# Generated by Django 3.2.7 on 2021-09-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210924_1413'),
        ('product', '0006_alter_productfeature_unique_together'),
        ('assortment', '0005_auto_20210914_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assortment', to='profile.company', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assortment', to='product.product', verbose_name='Товар'),
        ),
    ]
