name: diplom-app

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/web/app/requirements-dev.txt

      - name: Check Lint with flake8
        run: cd /home/runner/work/Netology_FinalDiplom/Netology_FinalDiplom/docker/web/app/shop && flake8 .

      - name: Pytest check
        run: cd docker/web/app/shop && pytest --cov=.
