# Generated by Django 3.2.7 on 2021-09-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0003_rename_amount_assortment_quantity'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Цена')),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assortment.assortment', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ')),
            ],
        ),
    ]
