# Generated by Django 3.2.7 on 2021-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Цена'),
        ),
    ]
